### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [user5497/C202309#2]
### 없는 파일
- project/week8/todo_manager.c
- project/week8/todo_manager_func.c
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week8/todo_manager.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week6/studentGrade
    - Error: use of undeclared identifier 'sumScore' [line 42]
         - 위 라인에 sumScore라는 변수가 없기 때문에 제대로 수행되지 않습니다.
         - 변수와 관련 함수 호출을 추가해주세요.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week6/studentGrade
    - Warning: non-void function does not return a value [line 38]
         - 위 라인에 있는 함수에 반환형이 int로 정의되어 있으나, 반환값이 없습니다. 반환값을 추가해주세요.

**Comment by user5497** [comment]
해결했습니다
